import { makeId, nowIso, db } from '../db.mjs';
import * as docAdapter from '../adapter/documents.mjs';
import * as sources from './sources.mjs';

const KEY = (cid) => `research_drafts_${cid}`;

function read(cid) {
  const row = db.prepare(
    'SELECT value FROM kv_store WHERE company_scope = ? AND key = ?',
  ).get(cid, KEY(cid));
  return row ? Object.values(JSON.parse(row.value)) : [];
}

function write(cid, drafts) {
  const map = Object.fromEntries(drafts.map((d) => [d.id, d]));
  db.prepare(
    `INSERT INTO kv_store(company_scope, key, value, revision, updated_at)
     VALUES(?, ?, ?, 1, ?)
     ON CONFLICT(company_scope, key) DO UPDATE
       SET value = excluded.value,
           revision = revision + 1,
           updated_at = excluded.updated_at`,
  ).run(cid, KEY(cid), JSON.stringify(map), nowIso());
}

export function list(cid) {
  return read(cid).sort((a, b) => b.created_at.localeCompare(a.created_at));
}

export function get(cid, id) {
  return read(cid).find((d) => d.id === id) ?? null;
}

export function create(cid, { title, sourceId, content }) {
  if (!title?.trim()) throw Object.assign(new Error('title is required'), { status: 400 });
  if (!content?.trim()) throw Object.assign(new Error('content is required'), { status: 400 });

  const draft = {
    id: makeId('rdr'),
    company_id: cid,
    title: title.trim(),
    source_id: sourceId ?? null,
    source_name: sourceId ? (sources.get(cid, sourceId)?.name ?? null) : null,
    content: content.trim(),
    status: 'pending-review',
    cms_document_id: null,
    created_at: nowIso(),
  };

  const drafts = read(cid);
  drafts.push(draft);
  write(cid, drafts);
  return draft;
}

export function discard(cid, id) {
  const drafts = read(cid);
  const idx = drafts.findIndex((d) => d.id === id);
  if (idx < 0) throw Object.assign(new Error('Draft not found'), { status: 404 });
  if (drafts[idx].status !== 'pending-review') {
    throw Object.assign(new Error('Only pending-review drafts can be discarded'), { status: 422 });
  }
  drafts[idx].status = 'discarded';
  write(cid, drafts);
  return drafts[idx];
}

export async function sendToCms(cid, draftId, productId, actorId) {
  const draft = get(cid, draftId);
  if (!draft) throw Object.assign(new Error('Draft not found'), { status: 404 });
  if (draft.status !== 'pending-review') {
    throw Object.assign(new Error('Only pending-review drafts can be sent to CMS'), { status: 422 });
  }
  if (!productId) throw Object.assign(new Error('productId is required'), { status: 400 });

  const doc = await docAdapter.save(
    {
      company_id: cid,
      product_id: productId,
      title: draft.title,
      type: 'guide',
      status: 'draft',
      metadata_json: JSON.stringify({
        researchSourceId: draft.source_id,
        researchDraftId: draftId,
      }),
    },
    actorId,
  );

  const drafts = read(cid);
  const idx = drafts.findIndex((d) => d.id === draftId);
  if (idx >= 0) {
    drafts[idx].status = 'sent-to-cms';
    drafts[idx].cms_document_id = doc.id;
    write(cid, drafts);
  }

  return { documentId: doc.id };
}

export function generateContent(source) {
  const name = source.name;
  const conceptLines = source.concepts
    ? source.concepts
        .slice(0, 4)
        .map((c) => `- **${c.charAt(0).toUpperCase() + c.slice(1)}** — browse related content`)
        .join('\n')
    : '- Browse available sections using the navigation';

  return `# Getting Started with ${name}

## Introduction

Welcome! This guide will help you get up and running with ${name} quickly.

${source.summary ? source.summary + '\n' : ''}
## Prerequisites

Before you begin, make sure you have:

- Access credentials provided by your account manager
- A modern web browser (Chrome, Firefox, or Edge recommended)
- Stable internet connection

## Step 1: Log In

Navigate to your company portal and enter your email and password.

## Step 2: Explore the Dashboard

Once logged in you'll see your dashboard — a high-level overview of all available content.

## Step 3: Find What You Need

${conceptLines}

## Step 4: Get Help

Reach out to your account manager or use the support section in your portal.

---

*Generated by DocPilot AI Research Center from: ${source.url ?? name}*`;
}
